import {
  env,
  runInDurableObject,
  runDurableObjectAlarm,
} from "cloudflare:test";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  __resetIncidentClientOverrides,
  __setIncidentClientOverrides,
} from "../src/incident";
import { FakeSlackClient } from "../src/clients/fakeSlack";
import { FakeSummarizer } from "../src/clients/fakeOpenai";

// One shared fake per test so we can seed inbound messages and inspect
// outbound posts across declare -> alarm -> resolve.
let slack: FakeSlackClient;
let summarizer: FakeSummarizer;

function stubFor(name: string) {
  const id = env.INCIDENT.idFromName(name);
  return env.INCIDENT.get(id);
}

function command(body: unknown): Request {
  return new Request("https://do/command", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
}

beforeEach(() => {
  slack = new FakeSlackClient();
  summarizer = new FakeSummarizer();
  __setIncidentClientOverrides({
    slack: () => slack,
    summarizer: () => summarizer,
    // sink is left to default: the real InternalStatusSink over the test D1.
  });
});

afterEach(() => {
  __resetIncidentClientOverrides();
});

describe("Incident DO lifecycle", () => {
  it("declare -> alarm posts an update to D1 + Slack -> resolve stops the loop", async () => {
    const incidentId = "inc_test_1";
    const stub = stubFor(incidentId);

    // 1) Declare.
    const declareRes = await stub.fetch(
      command({
        cmd: "declare",
        name: "API latency spike",
        body: "Users seeing 500s",
        id: incidentId,
      }),
    );
    const declared = (await declareRes.json()) as {
      incidentId: string;
      channelId: string;
    };
    expect(declared.incidentId).toBe(incidentId);
    expect(slack.created).toHaveLength(1); // channel created
    const channelId = declared.channelId;

    // Incident persisted to D1 (source of truth) with the opening update.
    const incRow = await env.DB.prepare(
      "SELECT * FROM incidents WHERE id = ?",
    )
      .bind(incidentId)
      .first<{ id: string; status: string; resolved_at: string | null }>();
    expect(incRow?.status).toBe("investigating");
    expect(incRow?.resolved_at).toBeNull();

    // An alarm must be armed after declare.
    await runInDurableObject(stub, async (_instance, state) => {
      expect(await state.storage.getAlarm()).not.toBeNull();
    });

    // 2) New channel activity, then advance the alarm.
    slack.seedMessage(channelId, "U_ONCALL", "DB connection pool exhausted");

    const ran = await runDurableObjectAlarm(stub);
    expect(ran).toBe(true);

    // The alarm summarized -> appended an update to D1 -> posted to Slack.
    const updatesAfterAlarm = await env.DB.prepare(
      "SELECT * FROM incident_updates WHERE incident_id = ? ORDER BY created_at",
    )
      .bind(incidentId)
      .all<{ body: string; status: string }>();
    // opening update + the alarm-generated update
    expect(updatesAfterAlarm.results.length).toBeGreaterThanOrEqual(2);
    const alarmUpdate = updatesAfterAlarm.results.at(-1)!;
    expect(alarmUpdate.status).toBe("monitoring");
    expect(summarizer.calls.length).toBe(1); // OpenAI was consulted once

    // It was posted to the incident channel.
    const postedTexts = slack.posted
      .filter((p) => p.channel === channelId)
      .map((p) => p.text);
    expect(postedTexts).toContain(alarmUpdate.body);

    // The loop rescheduled (still open).
    await runInDurableObject(stub, async (_instance, state) => {
      expect(await state.storage.getAlarm()).not.toBeNull();
    });

    // 3) Resolve.
    await stub.fetch(command({ cmd: "resolve", body: "Pool size increased" }));

    const resolvedRow = await env.DB.prepare(
      "SELECT status, resolved_at FROM incidents WHERE id = ?",
    )
      .bind(incidentId)
      .first<{ status: string; resolved_at: string | null }>();
    expect(resolvedRow?.status).toBe("resolved");
    expect(resolvedRow?.resolved_at).not.toBeNull();

    // The alarm was cancelled on resolve.
    await runInDurableObject(stub, async (_instance, state) => {
      expect(await state.storage.getAlarm()).toBeNull();
    });

    // 4) Even if an alarm somehow fires post-resolve, it must NOT reschedule.
    await runInDurableObject(stub, async (instance, state) => {
      await instance.alarm?.();
      expect(await state.storage.getAlarm()).toBeNull();
    });

    // No new update was generated by the post-resolve alarm tick.
    const finalUpdates = await env.DB.prepare(
      "SELECT COUNT(*) AS n FROM incident_updates WHERE incident_id = ?",
    )
      .bind(incidentId)
      .first<{ n: number }>();
    expect(finalUpdates?.n).toBe(updatesAfterAlarm.results.length + 1); // +1 = the resolve update only
  });

  it("declare is idempotent (a DO declares once)", async () => {
    const incidentId = "inc_test_2";
    const stub = stubFor(incidentId);

    const first = (await (
      await stub.fetch(command({ cmd: "declare", name: "X", id: incidentId }))
    ).json()) as { channelId: string };
    const second = (await (
      await stub.fetch(command({ cmd: "declare", name: "X again", id: incidentId }))
    ).json()) as { channelId: string };

    expect(second.channelId).toBe(first.channelId);
    expect(slack.created).toHaveLength(1); // channel created only once
  });
});
